# Generated by Django 2.2.1 on 2019-05-12 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_auto_20190502_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='currencydata',
            name='currency_long_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='currencydata',
            name='currency',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
