# Generated by Django 2.2.1 on 2019-05-12 21:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('market', '0004_auto_20190512_1220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersettings',
            name='username',
        ),
        migrations.AddField(
            model_name='usersettings',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
